name: python37
channels:
  - http://doocspkgs.desy.de/pub/doocsconda
  - ocelot-collab
  - defaults
dependencies:
  - alabaster=0.7.12
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - astroid=2.5
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - cached-property=1.5.2
  - certifi=2022.9.24
  - cffi=1.14.5
  - chardet=4.0.0
  - colorama=0.4.4
  - cryptography=3.4.7
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - dbus=1.13.18
  - decorator=5.0.9
  - defusedxml=0.7.1
  - docutils=0.17.1
  - entrypoints=0.3
  - expat=2.4.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2021.10.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.68.2
  - gmp=6.2.1
  - gmpy2=2.0.8
  - h5py=3.6.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - isort=5.8.0
  - jedi=0.17.0
  - joblib=1.1.0
  - jpeg=9b
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.15.2
  - keyring=23.0.1
  - kiwisolver=1.3.1
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libllvm11=11.1.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - llvm-openmp=12.0.0
  - llvmlite=0.37.0
  - locket=0.2.1
  - lz4-c=1.9.3
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.3
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - notebook=6.4.0
  - numba=0.54.1
  - numpy-base=1.20.2
  - numpydoc=1.1.0
  - ocelot=20.05.0
  - olefile=0.46
  - openssl=1.1.1s
  - packaging=20.9
  - pandocfilters=1.4.3
  - parso=0.8.2
  - partd=1.2.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.1.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pydoocs=2.0.6
  - pyflakes=2.3.1
  - pylint=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyqtgraph=0.11.0
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python.app=2
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=6.0
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.0.3
  - qtpy=1.9.0
  - readline=8.1
  - rope=0.18.0
  - scikit-image=0.18.3
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sphinx=4.0.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=3.3.6
  - spyder-kernels=0.5.2
  - sqlite=3.35.4
  - sympy=1.9
  - tbb=2021.4.0
  - terminado=0.9.4
  - testpath=0.4.4
  - threadpoolctl=2.2.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.2
  - tornado=6.1
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.36.2
  - wrapt=1.12.1
  - wurlitzer=2.1.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - altair==4.2.0
    - astunparse==1.6.3
    - asyncio==3.4.3
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.1
    - blinker==1.5
    - cachetools==5.0.0
    - charset-normalizer==3.0.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - codecov==2.1.12
    - commonmark==0.9.1
    - configspace==0.6.1
    - coverage==6.3.1
    - cython==0.29.28
    - deephyper==0.4.2
    - dm-tree==0.1.8
    - fabio==0.13.0
    - flatbuffers==2.0
    - gast==0.5.3
    - ghp-import==2.1.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.44.0
    - hdf5plugin==3.2.0
    - importlib-metadata==4.11.3
    - iniconfig==1.1.1
    - jinja2==2.11.3
    - jupytext==1.14.4
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - libclang==13.0.0
    - lxml==4.9.2
    - mako==1.1.6
    - markdown==3.3.6
    - markdown-it-py==2.1.0
    - markupsafe==1.1.1
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mergedeep==1.3.4
    - mkdocs==1.4.2
    - mkdocs-autorefs==0.4.1
    - mkdocs-jupyter==0.22.0
    - mkdocs-material==8.5.11
    - mkdocs-material-extensions==1.1.1
    - mkdocstrings==0.20.0
    - more-itertools==9.0.0
    - nbconvert==6.5.4
    - nbsphinx==0.8.8
    - numexpr==2.8.4
    - numpy==1.21.5
    - oauthlib==3.2.0
    - opencv-python==4.5.2.52
    - opt-einsum==3.3.0
    - pandas==1.3.5
    - pandoc==2.1
    - pickle5==0.0.12
    - platformdirs==2.5.0
    - plotly==5.11.0
    - pluggy==1.0.0
    - plumbum==1.7.2
    - ply==3.11
    - protobuf==3.20.1
    - py==1.11.0
    - pyarrow==10.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeck==0.8.0
    - pygments==2.14.0
    - pymdown-extensions==9.9.2
    - pympler==1.0.1
    - pyopencl==2022.1
    - pyopengl==3.1.5
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pytest==7.0.1
    - pytest-cov==3.0.0
    - pytest-qt==4.0.2
    - pytest-timeout==2.1.0
    - pytest-xvfb==2.0.0
    - python-decouple==3.7
    - pytools==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyvirtualdisplay==3.0
    - pyyaml-env-tag==0.1
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rich==13.0.1
    - rsa==4.8
    - semver==2.13.0
    - silx==1.0.0
    - skorch==0.12.1
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - streamlit==1.16.0
    - streamlit-aggrid==0.3.2
    - streamlit-toggle-switch==1.0.2
    - tables==3.6.1
    - tabulate==0.9.0
    - tenacity==8.1.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - timer==0.2.2
    - tinycss2==1.2.1
    - tinydb==4.7.1
    - tomli==2.0.1
    - torch==1.13.1
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - tzdata==2022.7
    - tzlocal==4.2
    - validators==0.20.0
    - watchdog==2.2.1
    - werkzeug==2.1.0
